version: '3'
services:
  populator:
    build:
      context: ./populator
      dockerfile: Dockerfile
    # environment:
    #   - POPULATOR_URL: "populator:8094"
    ports:
      - "8094:8088"
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      # DOC comment the following line and uncomment the next to run in a different base container
      # dockerfile: DockerfileScratch
      dockerfile: Dockerfile
    environment:
      - POPULATOR_URL=http://populator:8088
    ports:
      - "8092:8088"
    networks:
      - backend
  # langdb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 8084:27017
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: redhat
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: lirancohen
  #   networks:
  #     - backend
networks:
  backend:
    driver: bridge
