version: '3'
services:
  moviertriever:
    build:
      context: ./moviertriever
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8101:8101"
    networks:
      - backend
  searchperson:
    build:
      context: ./searchperson
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8100:8100"
    networks:
      - backend
  personcategory:
    build:
      context: ./personcategory
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8099:8099"
    networks:
      - backend
  actorcount:
    build:
      context: ./actorcount
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8098:8098"
    networks:
      - backend
  dbcounter:
    build:
      context: ./dbcounter
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8097:8097"
    networks:
      - backend
  populator:
    build:
      context: ./populator
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8088"
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - POPULATOR_URL=http://populator:8088
    ports:
      - "8092:8088"
    networks:
      - backend
  userfrontend1017:
    build:
      context: ./userfrontend1.0.17
      dockerfile: Dockerfile
    environment:
          - DBCOUNTER_URL=http://dbcounter:8097
          - ACTORCOUNTER_URL=http://actorcount:8098
          - PERSONCATEGORY_URL=http://personcategory:8099
          - SEARCHPERSON_URL=http://searchperson:8100
          - MOVIERETRIEVER_URL=http://moviertriever:8101
    ports:
      - "8095:8080"
    networks:
      - backend
  langdb:
    image: centos/mongodb-32-centos7
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADMIN_PASSWORD=lirancohen
      - MONGODB_USER=redhat
      - MONGODB_PASSWORD=lirancohen
      - MONGODB_DATABASE=imdb
    networks:
      - backend

  userfrontend1018:
    build:
      context: ./userfrontend1.0.18
      dockerfile: Dockerfile
    environment:
          - DBCOUNTER_URL=http://dbcounter:8097
          - ACTORCOUNTER_URL=http://actorcount:8098
          - PERSONCATEGORY_URL=http://personcategory:8099
          - SEARCHPERSON_URL=http://searchperson:8100
          - MOVIERETRIEVER_URL=http://moviertriever:8101
    ports:
      - "8050:8080"
    networks:
      - backend

  userfrontend1019:
    build:
      context: ./userfrontend1.0.19
      dockerfile: Dockerfile
    environment:
          - DBCOUNTER_URL=http://dbcounter:8097
          - ACTORCOUNTER_URL=http://actorcount:8098
          - PERSONCATEGORY_URL=http://personcategory:8099
          - SEARCHPERSON_URL=http://searchperson:8100
          - MOVIERETRIEVER_URL=http://moviertriever:8101
    ports:
      - "8051:8080"
    networks:
      - backend

  langdb:
    image: centos/mongodb-32-centos7
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADMIN_PASSWORD=lirancohen
      - MONGODB_USER=redhat
      - MONGODB_PASSWORD=lirancohen
      - MONGODB_DATABASE=imdb
    networks:
      - backend

networks:
  backend:
    driver: bridge
