version: '3'
services:
  populator:
    build:
      context: ./populator
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=langdb:27017
      - MONGO_DATABASE=imdb
      - MONGO_USER=redhat
      - MONGO_PASSWORD=lirancohen
    ports:
      - "8088"
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - POPULATOR_URL=http://populator:8088
    ports:
      - "8092:8088"
    networks:
      - backend
  langdb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=redhat
      - MONGO_INITDB_ROOT_PASSWORD=lirancohen
    networks:
      - backend
networks:
  backend:
    driver: bridge
