version: '3'
services:
  # gotest:
  #   build:
  #     context: .
  #     # DOC comment the following line and uncomment the next to run in a different base container
  #     # dockerfile: DockerfileScratch
  #     dockerfile: gottestgin/Dockerfile
  #   ports:
  #    - "8090:8080"
  frontend:
    build:
      context: ./frontend
      # DOC comment the following line and uncomment the next to run in a different base container
      # dockerfile: DockerfileScratch
      dockerfile: Dockerfile
    ports:
      - "8092:8088"
    networks:
      - backend
  # langdb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 8084:27017
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: redhat
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: lirancohen
  #   networks:
  #     - backend
networks:
  backend:
    driver: bridge
